import { MinutesOfMeetingsPage } from "@/features/meeting/components/minutes-of-meetings-page";
import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata({
  title: "Minutes of Meetings",
  description: "Browse and download professional minutes of meeting documents generated by AI for your Smart Meet workspace.",
  path: "/minutes-of-meetings",
  index: false,
});

export default function MinutesOfMeetingsRoute() {
  return <MinutesOfMeetingsPage />;
}
